"use client";
import { useEffect, useState } from "react";
import NavLinks from "@/components/dashboard/nav-links";
import { logout } from "@/app/actions";

export default function Sidebar({ role, activeStoreName, activeStoreLogo }: { role: "owner"|"manager"|"employee"; activeStoreName?: string | null; activeStoreLogo?: string | null }) {
  const ownerItems = [["/dashboard","Panel"],["/stores","Tiendas"],["/employees","Empleados"],["/managers","Encargados"],["/tasks","Tareas"],["/stock","Inventario"],["/events","Eventos"],["/accounting","Finanzas"],["/reports","Reportes"],["/purchase-orders","Pedidos"],["/settings","Configuración"]] as const;
  const managerItems = [["/dashboard","Panel"],["/employees","Empleados"],["/tasks","Tareas"],["/stock","Inventario"],["/events","Eventos"],["/accounting","Finanzas"],["/reports","Reportes"],["/purchase-orders","Pedidos"],["/settings","Configuración"]] as const;
  const employeeItems = [["/dashboard","Panel"],["/tasks","Tareas"],["/stock","Inventario"],["/events","Eventos"],["/reports","Reportes"],["/purchase-orders","Pedidos"],["/settings","Configuración"]] as const;
  const items = role === "owner" ? ownerItems : role === "manager" ? managerItems : employeeItems;
  const [collapsed, setCollapsed] = useState(false);
  useEffect(() => { const stored = localStorage.getItem("class_sidebar_collapsed"); const saved = stored === null ? window.matchMedia("(max-width: 768px)").matches : stored === "true"; setCollapsed(saved); document.documentElement.dataset.sidebar = saved ? "collapsed" : "expanded"; }, []);
  function toggle() { const next = !collapsed; setCollapsed(next); localStorage.setItem("class_sidebar_collapsed", String(next)); document.documentElement.dataset.sidebar = next ? "collapsed" : "expanded"; }
  return <><button type="button" onClick={toggle} className="fixed left-3 top-3 z-50 rounded-2xl border border-zinc-200 bg-white/90 px-3 py-2 text-sm text-zinc-800 shadow-lg backdrop-blur-xl dark:border-white/10 dark:bg-zinc-950/90 dark:text-white md:left-4 md:top-4">{collapsed ? "☰ Menú" : "×"}</button><aside className={`class-sidebar sticky top-0 z-40 h-screen overflow-y-auto border-r border-zinc-200 bg-white/95 p-4 pt-16 shadow-xl shadow-slate-200/60 backdrop-blur-2xl transition-all duration-200 dark:border-white/10 dark:bg-zinc-950/95 dark:shadow-black/20 md:p-6 md:pt-16 ${collapsed ? "pointer-events-none -translate-x-full opacity-0 md:w-0 md:p-0" : "translate-x-0 opacity-100"}`}><div className="mb-8 flex items-center gap-3"><div className="grid h-12 w-12 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-blue-500 to-emerald-400 text-sm font-semibold text-white shadow-lg shadow-blue-500/20">{activeStoreLogo ? <img src={activeStoreLogo} alt="Logo tienda" className="h-full w-full object-cover"/> : "C"}</div><div><h1 className="text-lg font-semibold tracking-tight text-zinc-950 dark:text-white">CLASS</h1><p className="max-w-36 truncate text-xs text-zinc-600 dark:text-zinc-400">{activeStoreName ?? "Workspace"}</p></div></div><div className="mb-5 rounded-2xl border border-blue-500/20 bg-blue-50 px-3 py-2 text-xs font-medium text-blue-700 dark:bg-blue-500/10 dark:text-blue-200">{role === "owner" ? "Workspace propietario" : role === "manager" ? "Encargado de tienda" : "Equipo operativo"}</div><NavLinks items={items}/><form action={logout} className="mt-8"><button className="w-full rounded-2xl border border-zinc-200 bg-white px-3 py-2.5 text-left text-sm text-zinc-800 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-white/10 dark:bg-white/5 dark:text-zinc-100">Cerrar sesión</button></form></aside></>;
}
