import { createDailyChecklist, createTask, toggleChecklistItem } from "@/app/actions";
import { resolveActiveStoreId } from "@/lib/server/store";
import Sidebar from "@/components/dashboard/sidebar";
import KanbanBoard from "@/components/tasks/kanban-board";

export default async function TasksPage() {
  const { supabase, storeId, role, activeStoreName, activeStoreLogo } = await resolveActiveStoreId();
  await supabase.rpc("ensure_daily_checklist_runs", { target_store: storeId });
  const canManage = role === "owner" || role === "manager";
  const [{ data: tasks }, { data: checklists }, { data: runItems }] = await Promise.all([
    supabase.from("tasks").select("id,title,completed,status").eq("store_id", storeId).order("created_at", { ascending: false }),
    supabase.from("daily_checklists").select("id,name,reset_time,business_days").eq("store_id", storeId).eq("active", true).order("created_at"),
    supabase.from("daily_checklist_run_items").select("id,title,completed,run_id,daily_checklist_runs!inner(checklist_id,run_date)").eq("store_id", storeId)
  ]);
  return <main className="min-h-screen bg-[var(--app-bg)] text-[var(--app-fg)] md:grid md:grid-cols-[280px_1fr]"><Sidebar role={role} activeStoreName={activeStoreName} activeStoreLogo={activeStoreLogo}/><section className="space-y-6 p-6 md:p-10"><header className="premium-card"><p className="text-sm font-semibold text-blue-600">📋 Operaciones • {activeStoreName}</p><h2 className="text-4xl font-semibold tracking-tight">Tareas</h2><p className="text-zinc-500 dark:text-zinc-400">Kanban con drag & drop y checklists diarios regenerados por plantilla.</p></header><form action={createTask} className="premium-card flex gap-2"><input name="title" required className="premium-input flex-1" placeholder="Nueva tarea operacional"/><input type="hidden" name="status" value="todo"/><button className="premium-button">Crear</button></form><KanbanBoard tasks={(tasks ?? []) as { id: string; title: string; completed: boolean; status: string }[]}/><section className="grid gap-4 xl:grid-cols-[360px_1fr]"><div className="premium-card"><h3 className="font-semibold">✅ Checklists diarios</h3><p className="mt-2 text-sm text-zinc-500">Hasta 3 checklists independientes con hora de reinicio y días activos.</p>{canManage ? <form action={createDailyChecklist} className="mt-4 grid gap-2"><input name="name" className="premium-input" placeholder="☀️ Turno mañana"/><input type="time" name="reset_time" defaultValue="08:00" className="premium-input"/><div className="grid grid-cols-4 gap-1 text-xs">{[[1,"L"],[2,"M"],[3,"X"],[4,"J"],[5,"V"],[6,"S"],[7,"D"]].map(([value,label]) => <label key={value} className="rounded-xl bg-zinc-100 p-2 dark:bg-white/10"><input type="checkbox" name="business_days" value={value} defaultChecked={Number(value) < 6}/> {label}</label>)}</div><textarea name="items" className="premium-input" placeholder={'Abrir caja\nRevisar stock\nLimpiar mostrador'}/><button className="premium-button">Crear checklist</button></form> : null}</div><div className="grid gap-4 md:grid-cols-3">{(checklists ?? []).map((list) => <article key={list.id} className="premium-card"><h4 className="font-semibold">{list.name}</h4><p className="mb-3 text-xs text-zinc-500">Reinicio: {list.reset_time}</p>{(runItems ?? []).filter((item: any) => item.daily_checklist_runs?.checklist_id === list.id).map((item: any) => <form key={item.id} action={toggleChecklistItem} className="mb-2 rounded-2xl bg-zinc-100 p-3 dark:bg-black/20"><input type="hidden" name="item_id" value={item.id}/><input type="hidden" name="completed" value={String(!item.completed)}/><button>{item.completed ? "✅" : "⬜"} {item.title}</button></form>)}</article>)}</div></section></section></main>;
}
