import { createStore } from "@/app/actions";
import Sidebar from "@/components/dashboard/sidebar";
import { resolveActiveStoreId } from "@/lib/server/store";

export default async function TiendasPage() {
  const { supabase, user, role, activeStoreName, activeStoreLogo } = await resolveActiveStoreId();
  if (role !== "owner") return null;
  const { data: stores } = await supabase.from("stores").select("id,name,address,created_at,logo_url").eq("owner_id", user.id).order("created_at", { ascending: false });
  const storeIds = (stores ?? []).map((store) => store.id);
  const { data: equipo } = storeIds.length ? await supabase.from("employees").select("store_id").in("store_id", storeIds) : { data: [] };
  const equipoCount = new Map<string, number>();
  (equipo ?? []).forEach((member) => equipoCount.set(member.store_id, (equipoCount.get(member.store_id) ?? 0) + 1));
  return <main className="min-h-screen bg-[var(--app-bg)] text-[var(--app-fg)] md:grid md:grid-cols-[280px_1fr]"><Sidebar role={role} activeStoreName={activeStoreName} activeStoreLogo={activeStoreLogo}/><section className="space-y-6 p-6 md:p-10"><header className="premium-card"><p className="text-sm font-semibold text-blue-600">🏪 Multi-tienda</p><h2 className="text-4xl font-semibold tracking-tight">Tiendas</h2><p className="mt-2 text-zinc-500 dark:text-zinc-400">Cards premium para administrar negocios independientes.</p></header><form action={createStore} className="premium-card grid gap-3 md:grid-cols-4"><input name="name" required className="premium-input" placeholder="Nombre tienda"/><input name="address" required className="premium-input" placeholder="Dirección"/><input name="description" className="premium-input" placeholder="Descripción"/><button className="premium-button">Crear tienda</button></form><a href="/seleccionar-tienda" className="inline-block rounded-2xl border border-zinc-200 bg-white px-4 py-3 text-sm shadow-sm transition hover:-translate-y-0.5 dark:border-white/10 dark:bg-white/5">Cambiar tienda activa</a><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(stores ?? []).map((store) => <article key={store.id} className={`premium-card ${store.name === activeStoreName ? "ring-2 ring-blue-500" : ""}`}><div className="mb-4 grid h-16 w-16 place-items-center overflow-hidden rounded-3xl bg-gradient-to-br from-blue-500 to-emerald-400 text-2xl text-white shadow-lg shadow-blue-500/20">{store.logo_url ? <img src={store.logo_url} alt="Logo" className="h-full w-full object-cover"/> : "🏪"}</div><p className="text-xl font-semibold">{store.name}</p><p className="text-sm text-zinc-500">📍 {store.address}</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-blue-500/10 px-3 py-1 text-xs text-blue-600">{store.name === activeStoreName ? "Tienda activa" : "Workspace independiente"}</span><span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs text-emerald-600">👥 {equipoCount.get(store.id) ?? 0} equipo</span></div></article>)}</div></section></main>;
}
