import { redirect } from "next/navigation";
import { createEmployee, createEmployeeSchedule, toggleEmployee, updateScheduleRequestStatus } from "@/app/actions";
import Sidebar from "@/components/dashboard/sidebar";
import { resolveActiveStoreId } from "@/lib/server/store";

type EmployeeRow = { id: string; name: string | null; email: string | null; active: boolean | null; role: string | null };
type ScheduleRow = { id: string; employee_id: string; shift_name: string; starts_at: string; ends_at: string; notes?: string | null; employees?: { name?: string | null } | null };
type RequestRow = { id: string; title: string; request_type: string; requested_date?: string | null; details?: string | null; status: string; employees?: { name?: string | null } | null };

function fmt(value: string) {
  return new Date(value).toLocaleString("es-AR", { weekday: "short", day: "2-digit", hour: "2-digit", minute: "2-digit" });
}

export default async function EmpleadosPage() {
  const { supabase, storeId, role, activeStoreName, activeStoreLogo } = await resolveActiveStoreId();
  if (role === "employee") redirect('/dashboard');
  const isOwner = role === "owner";
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const [{ data: employeeRows }, { data: scheduleRows }, { data: requestRows }] = await Promise.all([
    supabase.from("employees").select("id,name,email,active,role").eq("store_id", storeId).neq("role", "manager").order("created_at", { ascending: false }),
    supabase.from("employee_schedules").select("id,employee_id,shift_name,starts_at,ends_at,notes,employees(name)").eq("store_id", storeId).gte("starts_at", today.toISOString()).order("starts_at", { ascending: true }).limit(40),
    supabase.from("employee_schedule_requests").select("id,title,request_type,requested_date,details,status,employees(name)").eq("store_id", storeId).eq("status", "pending").order("created_at", { ascending: false }).limit(20)
  ]);
  const employees = (employeeRows ?? []) as EmployeeRow[];
  const schedules = (scheduleRows ?? []) as ScheduleRow[];
  const requests = (requestRows ?? []) as RequestRow[];
  const shifts = [...new Set(schedules.map((item) => item.shift_name))];

  return <main className="min-h-screen bg-[var(--app-bg)] text-[var(--app-fg)] md:grid md:grid-cols-[280px_1fr]"><Sidebar role={role} activeStoreName={activeStoreName} activeStoreLogo={activeStoreLogo}/><section className="space-y-6 p-6 md:p-10"><header className="premium-card flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-600">👥 Equipo operativo • {activeStoreName}</p><h2 className="text-4xl font-semibold tracking-tight">Empleados</h2><p className="mt-2 text-zinc-500 dark:text-zinc-400">Organizá empleados por turno, horarios semanales/mensuales y solicitudes de cambios.</p></div><span className="rounded-3xl bg-blue-500/10 px-5 py-4 text-2xl font-semibold text-blue-600">{employees.length}</span></header>

<form action={createEmployee} className="premium-card grid gap-3 md:grid-cols-5"><input name="name" required className="premium-input" placeholder="Nombre"/><input name="email" required className="premium-input" placeholder="Email"/><input name="temporary_password" required className="premium-input" placeholder="Contraseña temporal"/><select name="member_role" defaultValue="employee" className="premium-input"><option value="employee">Empleado</option>{isOwner ? <option value="manager">Encargado</option> : null}</select><button className="premium-button">Crear miembro</button></form>

<section className="premium-card"><h3 className="mb-3 font-semibold">🗓 Asignar horario / turno</h3><form action={createEmployeeSchedule} className="grid gap-3 md:grid-cols-3"><select name="employee_id" required className="premium-input"><option value="">Empleado</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select><input name="shift_name" required className="premium-input" placeholder="Turno mañana / noche"/><input type="datetime-local" name="starts_at" required className="premium-input"/><input type="datetime-local" name="ends_at" required className="premium-input"/><input name="notes" className="premium-input md:col-span-2" placeholder="Nota: Carlos cambia turno con Juan hoy"/><button className="premium-button md:col-span-3">Guardar horario</button></form></section>

<section className="grid gap-4 xl:grid-cols-2"><article className="premium-card"><h3 className="mb-3 font-semibold">🌅 Empleados por turno</h3>{shifts.length === 0 ? <p className="text-sm text-zinc-500">Todavía no hay turnos cargados.</p> : shifts.map((shift) => <details key={shift} open className="mb-3 rounded-2xl bg-zinc-100 p-3 dark:bg-black/20"><summary className="cursor-pointer font-medium">{shift}</summary><div className="mt-2 grid gap-2">{schedules.filter((item) => item.shift_name === shift).map((item) => <div key={item.id} className="rounded-xl bg-white p-3 text-sm dark:bg-white/5"><b>{item.employees?.name ?? "Empleado"}</b><p>{fmt(item.starts_at)} → {fmt(item.ends_at)}</p>{item.notes ? <p className="text-xs text-zinc-500">{item.notes}</p> : null}</div>)}</div></details>)}</article><article className="premium-card"><h3 className="mb-3 font-semibold">📩 Solicitudes de horario</h3>{requests.length === 0 ? <p className="text-sm text-zinc-500">No hay solicitudes pendientes.</p> : requests.map((request) => <div key={request.id} className="mb-2 rounded-2xl bg-blue-500/10 p-3"><p className="font-medium">{request.employees?.name ?? "Empleado"}: {request.title}</p><p className="text-xs text-zinc-500">{request.request_type} · {request.requested_date ?? "sin fecha"}</p>{request.details ? <p className="text-sm text-zinc-500">{request.details}</p> : null}<div className="mt-2 flex gap-2"><form action={updateScheduleRequestStatus}><input type="hidden" name="request_id" value={request.id}/><input type="hidden" name="status" value="approved"/><button className="rounded-xl bg-emerald-500/10 px-3 py-2 text-xs text-emerald-600">Aprobar</button></form><form action={updateScheduleRequestStatus}><input type="hidden" name="request_id" value={request.id}/><input type="hidden" name="status" value="rejected"/><button className="rounded-xl bg-red-500/10 px-3 py-2 text-xs text-red-600">Rechazar</button></form></div></div>)}</article></section>

<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{employees.length === 0 ? <div className="premium-card text-sm text-zinc-500">No hay empleados en esta tienda.</div> : null}{employees.map((employee) => <article key={employee.id} className="premium-card space-y-4"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full bg-gradient-to-br from-blue-600 to-cyan-400 text-xl font-semibold text-white shadow-lg shadow-blue-600/20">{employee.name?.[0] ?? "E"}</div><div><h3 className="font-semibold">{employee.name}</h3><p className="text-sm text-zinc-500">{employee.email}</p></div></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-blue-500/10 px-3 py-1 text-xs text-blue-600">{employee.role}</span><span className={`rounded-full px-3 py-1 text-xs ${employee.active ? "bg-emerald-500/10 text-emerald-600" : "bg-red-500/10 text-red-600"}`}>{employee.active ? "🟢 Activo" : "🔴 Desactivado"}</span><span className="rounded-full bg-zinc-500/10 px-3 py-1 text-xs text-zinc-500">🏪 {activeStoreName}</span></div><form action={toggleEmployee}><input type="hidden" name="employee_id" value={employee.id}/><input type="hidden" name="active" value={String(!employee.active)}/><button className="w-full rounded-2xl border border-zinc-200 px-4 py-3 text-sm transition hover:bg-zinc-100 dark:border-white/10 dark:hover:bg-white/10">{employee.active ? "Desactivar" : "Activar"}</button></form></article>)}</div></section></main>;
}
