import { redirect } from "next/navigation";
import Sidebar from "@/components/dashboard/sidebar";
import { createEncargado, removeEncargado, updateEncargado } from "@/app/profile-actions";
import { resolveActiveStoreId } from "@/lib/server/store";

export default async function EncargadosPage() {
  const { supabase, storeId, role, activeStoreName, activeStoreLogo } = await resolveActiveStoreId();
  if (role !== "owner") redirect('/dashboard');
  const { data: rows } = await supabase.from("employees").select("id,name,email,active").eq("store_id", storeId).eq("role", "manager").order("created_at", { ascending: false });
  return <main className="min-h-screen bg-[var(--app-bg)] text-[var(--app-fg)] md:grid md:grid-cols-[280px_1fr]"><Sidebar role={role} activeStoreName={activeStoreName} activeStoreLogo={activeStoreLogo}/><section className="space-y-6 p-6 md:p-10"><header className="premium-card"><p className="text-sm font-semibold text-blue-600">👔 Encargados • {activeStoreName}</p><h2 className="text-4xl font-semibold tracking-tight">Encargados de tienda</h2><p className="mt-2 max-w-3xl text-zinc-500 dark:text-zinc-400">Cada manager queda limitado a una sola tienda y puede gestionar operaciones sin controles multi-store.</p></header><form action={createEncargado} className="premium-card grid gap-3 md:grid-cols-4"><input name="name" required className="premium-input" placeholder="Nombre"/><input name="email" required className="premium-input" placeholder="Email"/><input name="temporary_password" required className="premium-input" placeholder="Contraseña temporal"/><button className="premium-button">➕ Crear encargado</button></form><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(rows ?? []).length === 0 ? <div className="premium-card text-sm text-zinc-500">Aún no hay encargados en esta tienda.</div> : null}{(rows ?? []).map((manager) => <article key={manager.id} className="premium-card space-y-4 border-blue-500/20"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-blue-600 text-2xl text-white shadow-lg shadow-blue-600/20">👔</div><div><div className="flex items-center gap-2"><h3 className="font-semibold">{manager.name}</h3><span className="rounded-full bg-blue-500/10 px-2 py-1 text-xs text-blue-600">Encargado</span></div><p className="text-sm text-zinc-500">{manager.email}</p></div></div><form action={updateEncargado} className="grid gap-2"><input type="hidden" name="manager_id" value={manager.id}/><input type="hidden" name="active" value={String(manager.active)}/><input name="name" defaultValue={manager.name} className="premium-input"/><button className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm dark:border-white/10">✏️ Guardar</button></form><div className="grid grid-cols-2 gap-2"><form action={updateEncargado}><input type="hidden" name="manager_id" value={manager.id}/><input type="hidden" name="name" value={manager.name}/><input type="hidden" name="active" value={String(!manager.active)}/><button className="w-full rounded-2xl border border-zinc-200 px-4 py-3 text-sm dark:border-white/10">🔒 {manager.active ? "Desactivar" : "Activar"}</button></form><form action={removeEncargado}><input type="hidden" name="manager_id" value={manager.id}/><button className="w-full rounded-2xl bg-rose-500/10 px-4 py-3 text-sm text-rose-600">🗑 Eliminar</button></form></div></article>)}</div></section></main>;
}
